# This is a basic workflow to help you get started with Actions

name: RequestToRep


on:
  
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on:  macos-latest

    steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 16
         uses: actions/setup-java@v2
         with:
          java-version: '16'
          distribution: 'adopt'
       - name: Validate Gradle wrapper
         uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
       - name: Build with Gradle
         run: ./gradlew test
       - name: Archive testss results
         uses: actions/upload-artifact@v2
         with:
          name: code-tests-report
          path: build/reports/tests/test/
       - name: Archive code coverage results
         uses: actions/upload-artifact@v2
         with:
          name: code-coverage-report
          path: build/jacocoHtml/
      # - name: Download all workflow run artifacts
       #  uses: actions/download-artifact@v2


         
         
